sudo: false
dist: trusty
language: python
python:
- 3.6.6
#before_install:
#  - env
#  - openssl version
#  - python -c "import ssl; print('SSSSSSSSSL', ssl.OPENSSL_VERSION)"
install:
- sudo apt-get update
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install --force-reinstall etk  # For some reason etk is not installed properly from requirements on Travis
script:
- python -m spacy download en_core_web_sm
- python -m unittest backend.backend_code.unit_tests.test_rdf_generation
- python -m unittest backend.backend_code.unit_tests.test_json_results
notifications:
  slack:
    secure: kRH2jEazF21qeFEp0Z3k+HjMWYhhSXd1iw+vOJfHbTsMPpFMuOPt/PAVQCVFvigFuGC/7H5T/Y/c0GFgY1ST+Vm4o855uoH/ekqDlbloFxAtO8jeIOkF59D+2eS6DNEBKPEtVoxAavW6kSjIrCab9+96199hNvcwOzv+ceZi52OX/EGglpw5Ys+zfyLIObImwcyV0NvydjMkSL13WIZ9lfIL9AfknFuFXI766XjtLukGQctifHwwrXQgYS79K18bKb8MUeQ27xs8PvXX2ZX7iuLeXTXSrDlPZP4dPw9D3QmBeLa/u8WQtm9elIrExwsfOj0jDyR70RutRpeD8xh0iIYSXGWYsnKHNi1jMmezZWe/gD5CgZeCIPzAcvrMv9dGbOi4PL97fV69YVbOwCSd9mrfU9pAQ8kl/idlQeF9LWasglDCWcKZcc4/iJW09bveMFtefxO9Y2SFv4hl+XErVRwdKZO0Q68SaFSX1442Uv6ZJ82doI2OVd137KiQ7sSZLNfUmG6uYQSC7eo1TRr6BFkjNYqqMIH4XambgwOYkD9dZX818/BkcbNkAadDP1hS9C1bvPPPm3MsesJC4rfZlC6Zlm/paB1+ijlfUmxtFVl2O2tHV3cKbf5kJXap0qdWD6Yuyr3eoOhEzTvinV3tN/JkbwA+2h/YMH9GbIRqpeA=
